---
kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  labels:
    service: frontend-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30041
  selector:
    service: frontend-service