server:
  port: 8090

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

consumed:
  microservice:
    name: "simple-spring-boot-provider.local.pcfdev.io"
    url: "http://localhost:8080/"
