---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend-service
  template:
    metadata:
      name: frontend-app
      labels:
        name: frontend-app
        app: frontend-app
        service: frontend-service
    spec:
      containers:
      - image: jaegertracing/jaeger-agent:1
        name: jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        command:
        - "/go/bin/agent-linux"
        - "--collector.host-port=jaeger-collector:14267"
      - name: frontend-app
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        imagePullPolicy: Always
        image: chaosiq/demos-frontend-app:0.8.0
        env:
        - name: PG_ADDR
          value: frontend-db.default.svc.cluster.local:5432
        - name: PG_USERNAME
          value: frontend
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: frontend.frontend-db.credentials
              key: password
        livenessProbe:
          httpGet:
            path: "/live"
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 0.4
            memory: 64Mi
          requests:
            cpu: 0.2
            memory: 64Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1